name       : xone
version    : 0.3
release    : 1
source     :
    - https://github.com/medusalix/xone/archive/refs/tags/v0.3.tar.gz : 993f6b2b07c3236ce283d5de4da47dbfc16a86e056af504a4958d87f718ece20
homepage   : https://github.com/medusalix/xone
license    : GPL-2.0-or-later
component  :
    - kernel.drivers
    - current: kernel.drivers
    - common : system.utils
    - modaliases : kernel.drivers
summary    : 
    - Linux kernel driver for Xbox One and Xbox Series X|S accessories
    - current: xone for the linux-current kernel
    - common : Common component for xone kernel modules
    - modaliases : These files are used by the Software Center for hardware detection
description: |
    xone is a Linux kernel driver for Xbox One and Xbox Series X|S accessories. It serves as a modern replacement for xpad, aiming to be compatible with Microsoft's Game Input Protocol.
builddeps  :
    - pkgconfig(alsa)
    - linux-current
    - linux-current-headers
patterns   :
    - common : /*
    - current : /lib/modules/*.current
    - modaliases : /usr/share/linux-driver-management/modaliases
rundeps    :
    - common :
        - upower
    - xone-common
    - current : 
        - xone-common
setup      : |
    # Prep build dirs for lts and current
    pushd ../
    #cp -a "xone-${version}" lts-build # This will be needed when we have linux-lts >= 4.15
    cp -a "xone-${version}" current-build
    popd
build      : |
    # lts will be added in the future
    pushd current-build
    KVER=%kernel_version_current%
    %make -C /lib/modules/$KVER/build M=$PWD

    # Generate modaliases
    mkmodaliases "${package}" -o "${package}.modaliases" *.ko
    popd
install    : |
    # lts will be added in the future
    pushd current-build
    KVER=%kernel_version_current%
    install -D -d -m 00644 $installdir/lib/modules/$KVER/drivers/input/joystick
    install -D -m 00644 *.ko $installdir/lib/modules/$KVER/drivers/input/joystick/.
    install -D -m 00644 install/modprobe.conf $installdir/usr/lib/modprobe.d/xone-blacklist.conf 
    install -D -m 00755 install/firmware.sh $installdir/usr/bin/xone-get-firmware.sh
    popd

    # Install modaliases for LDM
    install -D -m 00644 current-build/${package}.modaliases $installdir/usr/share/linux-driver-management/modaliases/${package}.modaliases
