name       : zoom
version    : 6.1.11.1545
release    : 5
source     :
    - https://zoom.us/client/6.1.11.1545/zoom_x86_64.tar.xz : b4a743ff8360ab589e8cf6538ebfb39f461a459dad2f63a443e4ff608e88a0a9
license    : Proprietary
component  : network.web
summary    : Zoom video conference client
description: |
    Zoom video conference client.
# For rundeps detection only
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libglvnd)
    - pkgconfig(Qt53DCore)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
install    : |
    install -dm00755 $installdir/usr/share/zoom
    cp -r $PWD $installdir/usr/share

    install -Dm00644 $pkgfiles/ZoomLauncher.desktop -t $installdir/usr/share/applications
    install -Dm00644 $pkgfiles/us.zoom.Zoom.64.png $installdir/usr/share/icons/hicolor/64x64/apps/us.zoom.Zoom.png
    install -Dm00644 $pkgfiles/us.zoom.Zoom.96.png $installdir/usr/share/icons/hicolor/96x96/apps/us.zoom.Zoom.png
    install -Dm00644 $pkgfiles/us.zoom.Zoom.128.png $installdir/usr/share/icons/hicolor/128x128/apps/us.zoom.Zoom.png
    install -Dm00644 $pkgfiles/us.zoom.Zoom.256.png $installdir/usr/share/icons/hicolor/256x256/apps/us.zoom.Zoom.png
